name: qr_scan_ieee
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8 
  mobile_scanner:
  intl: 
  lottie: ^3.3.1
  qr_scanner_overlay: ^0.0.2
  dio: ^5.8.0+1
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.14.3
  internet_connection_checker_plus: ^2.7.2

dev_dependencies:
  hive_ce_generator: 
  build_runner: 
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/qr.png"

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/
  fonts:
    - family: ltim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
